### ISSUE TITLE
Provide a Way to Set Preferences

### ISSUE THREAD

**Issue by git-afsantos** [git-afsantos/haros#12]
A configuration/preferences file makes sense at this point. This could be a way to enable/disable plugins by default, providing preferences to plugins, or even suppressing certain metrics and rules.

```yaml
analysis:
    ignore:
        rules:
            - plugin:rule_id
        files:
            - package:relative/path/to/file
viz:
    host: localhost
    port: 8080
plugins:
    plugin_name:
        whatever: the plugin needs
```
