### ISSUE TITLE
Catkin_tools compatibility

### ISSUE THREAD

**Issue by AlexisTM** [git-afsantos/haros#97]
`catkin_tools` works slightly differently from `catkin_make` but is also one of the most used tools as it proposes Toolchains, profiles and workspace extension (the main features we use).

How are we supposed to configure HAROS for catkin_tools? How `ROS_WORKSPACE` (unset) supposed to be? How can we handle the face we have the source and build folder apart from each other (depending on catkin_tools config).

**Comment by git-afsantos** [comment]
Indeed, HAROS has not received built-in support for `catkin_tools` yet, but I think you can work around it. I assume you want to try model extraction, and thus need the workspace and build location.

In the HAROS home directory (defaults to `~/.haros`), you will find a `configs.yaml` file.
In this file, you can un-comment and edit a few lines to point to the right places.

```yaml
workspace: '/path/to/ws'
cpp:
    compile_db: '/path/to/ws/build'
```

I am not sure if the CMake parser will give you trouble still. Let me know.

**Comment by AlexisTM** [comment]
https://github.com/rosin-project/haros_catkin/tree/735a6c6316d9b72754085bc30739accad673354f

**Comment by AlexisTM** [comment]
When doing so, it finds the packages in `/tmp/src/install_x64` instead of `/home/alexis/workspace/src` (The install folder that has been sourced)

```yaml
%YAML 1.1
---
workspace: "/home/alexis/workspace/src"
cpp:
    parser_lib: '/usr/lib/llvm-11/lib'
    std_includes: '/usr/lib/llvm-11/lib/clang/11.0.0/include'
    compile_db: '/tmp/src/build_x64'
py:
    compile_db: '/tmp/src/build_x64'
packages:
  - base
  - ncc
```
